/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "background": "#f8f9fb",
        "surface": "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434655",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#595e6f",
        "secondary-container": "#dbdff4",
        "secondary-fixed": "#dee2f7",
        "secondary-fixed-dim": "#c1c6da",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5d6274",
        "on-secondary-fixed": "#161b2a",
        "on-secondary-fixed-variant": "#414657",
        "tertiary": "#006242",
        "tertiary-container": "#007d55",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bdffdb",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#f0f1f3",
        "success": "#10b981",
        "success-container": "#d1fae5",
        "on-success": "#ffffff",
        "on-success-container": "#065f46",
      },
      spacing: {
        "sidebar-width": "260px",
        "margin-page": "1.5rem",
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        "stack-xs": "0.25rem",
        "gutter": "1rem",
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "sm": "0.125rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontFamily: {
        "ui": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "table-cell": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
